Add apptainer_wrapper and make variables SING_IMAGE and SING_FLAGS into CONTAINER_IMAGE and CONTAINER_FLAGS

diff --git a/bin/singularity_wrapper b/bin/singularity_wrapper
--- a/bin/singularity_wrapper
+++ b/bin/singularity_wrapper
@@ -24,36 +24,47 @@
 
 #
 # Singularity wrapper is a small script that runs commands in image
-# found by environment variable $SING_IMAGE. Flags such as bind mounts,
-# nvidia flags etc. can be set in $SING_FLAGS-environment variable.
+# found by environment variable $CONTAINER_IMAGE. Flags such as bind mounts,
+# nvidia flags etc. can be set in $CONTAINER_FLAGS-environment variable.
 #
+
+command -v apptainer 2>&1 > /dev/null
+APPTAINER_CHECKUP=$?
+if [[ $APPTAINER_CHECKUP -eq 0 ]]; then
+  CONTAINER_CMD=apptainer
+else
+  CONTAINER_CMD=singularity
+fi
+
+WRAPPER_NAME=$(basename $0)
 
 usage() {
     cat << EOF
 
-singularity_wrapper
+$WRAPPER_NAME
 
   USAGE:
 
     To run a command in an image:
-        singularity_wrapper exec <command>
+        $WRAPPER_NAME exec <command>
 
     To run the image using its preferred method:
-        singularity_wrapper run
+        $WRAPPER_NAME run
 
     To launch an interactive shell (e.g. /bin/bash) in the image:
-        singularity_wrapper shell <shell>
+        $WRAPPER_NAME shell <shell>
 EOF
 }
 
-if [ -z "$SING_IMAGE" ] ; then
-  echo "Cannot find a singularity image as \$SING_IMAGE has not been set."
+
+if [ -z "$CONTAINER_IMAGE" ] ; then
+  echo "Cannot find a ${CONTAINER_CMD} image as \$CONTAINER_IMAGE has not been set."
   usage
   exit 1
 fi
 
-if [ ! -f "$SING_IMAGE" ] ; then
-  echo "Cannot find a singularity image as \$SING_IMAGE does not point to an image file."
+if [ ! -f "$CONTAINER_IMAGE" ] ; then
+  echo "Cannot find a ${CONTAINER_CMD} image as \$CONTAINER_IMAGE does not point to an image file."
   usage
   exit 1
 fi
@@ -67,20 +78,20 @@ fi
 
 case "$1" in
     exec)
-        singularity exec $SING_FLAGS $SING_IMAGE "${@:2}"
+        ${CONTAINER_CMD} exec $CONTAINER_FLAGS $CONTAINER_IMAGE "${@:2}"
         exit $?
         ;;
     shell)
         if [[ $nopts -lt 2 ]]; then
-            singularity shell $SING_FLAGS $SING_IMAGE
+            ${CONTAINER_CMD} shell $CONTAINER_FLAGS $CONTAINER_IMAGE
             exit $?
         else
-            singularity shell -s $2 $SING_FLAGS $SING_IMAGE
+            ${CONTAINER_CMD} shell -s $2 $CONTAINER_FLAGS $CONTAINER_IMAGE
             exit $?
         fi
         ;;
     run)
-        singularity run $SING_FLAGS $SING_IMAGE "${@:2}"
+        ${CONTAINER_CMD} run $CONTAINER_FLAGS $CONTAINER_IMAGE "${@:2}"
         exit $?
         ;;
     *)
